CREATE TABLE accounts (
    account_no NUMBER PRIMARY KEY, 
    holder_name VARCHAR2(100), 
    balance NUMBER(10,2) CHECK (balance >= 0)
);

CREATE TABLE transactions (
    transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_account NUMBER,
    to_account NUMBER,
    amount NUMBER(10,2),
    transaction_date TIMESTAMP DEFAULT SYSTIMESTAMP
);

INSERT INTO accounts VALUES (1001, 'Amit Sharma', 5000.00);
INSERT INTO accounts VALUES (1002, 'Priya Verma', 7500.50);
INSERT INTO accounts VALUES (1003, 'Rahul Singh', 12000.75);
INSERT INTO accounts VALUES (1004, 'Neha Gupta', 3000.00);
INSERT INTO accounts VALUES (1005, 'Karan Mehta', 15000.25);
COMMIT;
SELECT * FROM accounts;

CREATE OR REPLACE PROCEDURE transfer_funds(
    p_from_acc NUMBER,
    p_to_acc NUMBER,
    p_amount NUMBER
) AS
    v_balance NUMBER;
BEGIN
    IF p_from_acc = p_to_acc THEN
        RAISE_APPLICATION_ERROR(-20004, 'Sender and receiver cannot be the same.');
    END IF;
    SELECT balance INTO v_balance FROM accounts WHERE account_no = p_from_acc;
    IF v_balance < p_amount THEN
        RAISE_APPLICATION_ERROR(-20001, 'Insufficient balance.');
    END IF;
    UPDATE accounts SET balance = balance - p_amount WHERE account_no = p_from_acc;
    UPDATE accounts SET balance = balance + p_amount WHERE account_no = p_to_acc;
    INSERT INTO transactions (from_account, to_account, amount)
    VALUES (p_from_acc, p_to_acc, p_amount);

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Transfer successful.');

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20002, 'Invalid account number.');
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20003, 'Transaction failed: ' || SQLERRM);
END;
/


BEGIN
    transfer_funds(1001, 1002, 900);
END;
/

SET SERVEROUTPUT ON;
DECLARE
    v_account_no accounts.account_no%TYPE := &account_no;
    v_balance    accounts.balance%TYPE;
BEGIN
    SELECT balance INTO v_balance FROM accounts WHERE account_no = v_account_no;
    
    DBMS_OUTPUT.PUT_LINE('Account Number: ' || v_account_no);
    DBMS_OUTPUT.PUT_LINE('Available Balance: ' || v_balance);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Account not found');
END;
/

DECLARE
    v_account_no NUMBER := &account_no;
BEGIN
    FOR rec IN (
        SELECT * FROM transactions 
        WHERE from_account = v_account_no OR to_account = v_account_no
    )
    LOOP
        DBMS_OUTPUT.PUT_LINE(
            rec.transaction_id || ' ' || 
            rec.from_account || ' ' || 
            rec.to_account || ' ' || 
            rec.amount || ' ' || 
            rec.transaction_date
        );
    END LOOP;
END;
/

CREATE OR REPLACE FUNCTION get_balance(p_acc_no NUMBER) 
RETURN NUMBER 
AS
    v_balance NUMBER;
BEGIN
    SELECT balance 
    INTO v_balance 
    FROM accounts 
    WHERE account_no = p_acc_no;

    RETURN v_balance;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN -1; 
END;
/

SELECT get_balance(1001) AS balance FROM dual;


CREATE OR REPLACE PROCEDURE transfer_funds (
    p_from_acc IN NUMBER,
    p_to_acc   IN NUMBER,
    p_amount   IN NUMBER
) 
IS
    v_balance NUMBER;
    v_txn_id  NUMBER;
BEGIN
    IF p_from_acc = p_to_acc THEN
        RAISE_APPLICATION_ERROR(-20004, 'Sender and receiver cannot be the same.');
    END IF;

    IF p_amount > 10000 THEN
        RAISE_APPLICATION_ERROR(-20005, 'Transfer amount exceeds the limit of ₹10,000.');
    END IF;

    SELECT balance INTO v_balance 
    FROM accounts 
    WHERE account_no = p_from_acc;

    IF v_balance < p_amount THEN
        RAISE_APPLICATION_ERROR(-20001, 'Insufficient balance.');
    END IF;
    UPDATE accounts SET balance = balance - p_amount WHERE account_no = p_from_acc;
    UPDATE accounts SET balance = balance + p_amount WHERE account_no = p_to_acc;
    SELECT NVL(MAX(transaction_id), 0) + 1 INTO v_txn_id FROM transactions;

    INSERT INTO transactions (transaction_id, from_account, to_account, amount, transaction_date)
    VALUES (v_txn_id, p_from_acc, p_to_acc, p_amount, SYSDATE);

    COMMIT;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20002, 'Invalid account number.');
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/


CREATE OR REPLACE PROCEDURE display_monthly_txns (
    p_acc_no NUMBER,
    p_month_year VARCHAR2 
) AS
BEGIN
    FOR rec IN (
        SELECT * FROM transactions 
        WHERE (from_account = p_acc_no OR to_account = p_acc_no)
        AND TO_CHAR(transaction_date, 'MM-YYYY') = p_month_year
    )
    LOOP
        DBMS_OUTPUT.PUT_LINE(
            'Transaction ID: ' || rec.transaction_id || ' | ' ||
            'Sender: '         || rec.from_account    || ' | ' ||
            'Receiver: '       || rec.to_account      || ' | ' ||
            'Amount: '         || rec.amount          || ' | ' ||
            'Date: '           || rec.transaction_date
        );
    END LOOP;
END;
/

BEGIN
    display_monthly_txns(1009, '04-2026');
END;
/
