select * from dual;
select initcap('abcedfg') from dual;
SELECT UPPER('System is running SQL!') FROM dual;
SELECT LOWER('ORACLE DATABASE') FROM dual;
SELECT INITCAP('database management system') FROM dual;
SELECT LENGTH('SQLplus') FROM dual;
SELECT SUBSTR('Nagpur', 3, 4) FROM dual;
SELECT INSTR('Maharashtra', 'a') FROM dual;
SELECT CONCAT('SQL', 'PLUS') FROM dual;
SELECT CONCAT('SQL', 'Database') FROM dual;
select TRIM('*' FROM '*****abscgdjd***') from dual;
select rtrim('*****abcdefghijk****','*') from dual;
select ltrim('*****abcdefghijk****','*') from dual;
select MAX(salary), dept_id from Emp3 GROUP BY dept_id;
select MIN(salary), dept_id from Emp3 GROUP BY dept_id;
select AVG(salary), dept id from Emp3 GROUP BY dept_id;
select AVG(salary), dept_id from Emp3 GROUP BY dept_ID HAVING dept_id = 'D01';
select AVG(salary), dept_id from Emp3 GROUP BY dept_ID HAVING dept_id = 'D03';
select MAX(salary), dept_id from Emp3 GROUP BY dept ID HAVING dept_id = 'D03';
select * from dual;
select round (12345, 2) from dual;
select round (12345.67890,2) from dual;
select mod(9,2) from dual;
select mod(9,2) "mod" from dual;
select exp(9) from dual;
select floor (320.345) from dual;
select ceil(320.345) from dual;
select ceil(1000.92735330) from dual;
select sqrt(1123454) from dual;
select mod (2345,2) from dual;
select mod (2345, 4) from dual;
select mod (2345232,9) from dual;
select abs (235362) from dual;
select abs(235362.28191) from dual;
select SYSDATE from dual;
select NEXT_DAY('12-FEB-2026'); select NEXT_DAY('12-FEB-2026')
select NEXT_DAY('12-FEB-2026',2); select NEXT_DAY('12-FEB-2026', 2)
select ADD_MONTHS(SYSDATE, 53) from dual;
select NEXT_DAY(SYSDATE, 'thursday') from dual;
select NEXT_DAY(SYSDATE, 'FRIDAY') from dual;
select NEXT_DAY('12-FEB-30', 'FRIDAY') from dual;
select MONTHS_BETWEEN('11-FEB-2026', '11-FEB-2045') from dual;
select MONTHS_BETWEEN('11-FEB-2045', '11-FEB-2026') from dual;
select LAST_DAY(SYSDATE) from dual;
select LAST_DAY('12-FEB-2043') from dual;
select TO_NUMBER('1234562') from dual;
select TO_CHAR('DATASCIENCE') from dual;
create table Emp3(e_id varchar2(5), name varchar2(100), dept_id varchar(5), dept_name varchar2(20), job varchar2(20), salary number, D_D_J date);
select * from Emp3;
select COUNT(salary) from Emp3;
select DISTINCT COUNT(salary) from Emp3;
select COUNT(e_id) from Emp3;
select COUNT (DISTINCT salary) from Emp3;
select COUNT (salary) from Emp3;
select DISTINCT COUNT(salary) from Emp3;
select COUNT(e_id) from Emp3;
select COUNT (DISTINCT salary) from Emp3;
select COUNT(DISTINCT job) from Emp3;
select COUNT (DISTINCT job) from Emp3;
select COUNT (DISTINCT dept_name) from Emp3;
select COUNT (DISTINCT D_O_J) from Emp3;
select SUM(salary) from Emp3;
select MIN(salary) from Emp3;
select MAX(salary) from Emp3;
select AVG(salary) from Emp3;
select MIN(D_O_J), dept_id from Emp3 GROUP BY dept_id HAVING dept_id = 'D02';
select MIN(D_O_J) from Emp3 GROUP BY dept_id;
select dept_id, name, MIN(D_O_J) from Emp3 GROUP BY dept_id; select dept_id, name, MIN(D_O_J) from Emp3 GROUP BY dept_id
select dept_id, MIN(D_O_J) from Emp3 GROUP BY dept_id;
select MAX(salary) from Emp3 where dept_name = 'Research';
select AVG(salary) from Emp3 where job 'Data Analyst';
select MIN(salary) from Emp3 where dept_name = 'Marketing';
select MIN(salary) from Emp3 GROUP BY dept_name HAVING dept_name = 'Marketing';
select MAX(salary) from Emp3 GROUP BY dept_name HAVING dept_name 'Research';
select AVG(salary) from Emp3 GROUP BY job HAVING job 'Data Analyst';
